#
# This is a kinda "defaults" config.
# These variables should probably be changed, but as this is in mainline git,
# it's not very useful to edit here.
#
# Simplest (for now) wat to change this is through the CustomBundle, but
# I will try to come up with a way to change values here without installing
# the CustomBundle.
#
# Guess this is possible to get from .env(.local)
#
parameters:
    # You may want to change these.
    # Languange - No translations yet, so this is mere sugar.
    locale: en_GB

    # Javascripts Intl uses two-letter locale. And it should be decided by the
    # browser/client. Somehow that is broken.
    javascript_locale: en

    # Fullcalendar also use locale, but it may not have what you set above.
    # Check https://github.com/fullcalendar/fullcalendar/tree/master/locales
    # Use the filename without .js
    # If you set "all" it will load the all.js file instead. It's close to 200K
    # where the separate files are 3K.
    fullcalendar_locale: en-gb

    # New users has to be connected to something by default. If it's a crew
    # member you want to connect it to your organization with a default role.
    # (This is a hen and egg situation since you haven't created your
    # organization when you set up this application. But there is a solutaion
    # to that. The name and role you put here will be created by the
    # once:create-base-data command.
    #
    # This is also what defines a crew member.
    internal_organization:
        name: "%env(INTERNAL_ORGANIZATION)%"
        default_role: "%env(DEFAULT_ROLE)%"
        # If you set this to false the organization and role above will be
        # added to all new crew members and no option to set others will be
        # shown. I'd guess this will not be used much.
        allow_external_crew: "%env(ALLOW_EXTERNAL_CREW)%"

    # This is for setting up the address fields. Different countries has
    # different needs, so we need somewhere for defining those needs.
    # Fields you can use is in Entity/EmbeddableAddress in the CrewCallBundle
    # code.
    # Country differs that it will not be showwn if it is the default country.
    # The values here is the ones shown in the input and edit forms.
    addressing:
        # Mostly, postal address as an extra address is not used. If you want
        # it, set it to true.
        use_postal_address: false
        # But I'll stick with Norway as there is enough US centric software out
        # there. Choosing FR or DE would end up in a diplomatic conflict in
        # Strasbourg.
        default_country_code: NO
        default_country_name: Norway
        format:
            - ['addressLine1']
            - ['addressLine2']
            - ['postalCode', 'postalName']
            # This is the country code. Which may not be very useful.
            - ['country']

    #
    # Which of the available fields are you interested in showing and using?
    # The compulsory: Username, First Name, Last name
    #
    # This is set up for a typical volunteering situation. I presume an
    # employee relation need a few more fields or all.
    #
    # It can also handle attributes, for more customization.
    # attribute: true and you then need label: "Foo Bar"
    # 
    personfields:
        date_of_birth:
            enabled: false
            attribute: false
            user_editable: true
        diets:
            enabled: false
            attribute: false
            user_editable: true
        workload_percentage:
            enabled: false
            attribute: false
            user_editable: false
        nationality:
            enabled: false
            attribute: false
            user_editable: true
        emergency_contact:
            enabled: false
            attribute: false
            user_editable: true
        email:
            enabled: true
            attribute: false
            user_editable: true
        mobile_phone_number:
            enabled: true
            attribute: false
            user_editable: true
        address:
            enabled: true
            attribute: false
            user_editable: true
        home_phone_number:
            enabled: false
            attribute: false
            user_editable: false
        postal_address:
            enabled: false
            attribute: false
            user_editable: false
        # Not entirely personfields, but nice to configure.
        hours:
            enabled: true
            attribute: false
            user_editable: false
        profile_picture:
            enabled: true
            attribute: false
            user_editable: true
        # Not that commenting this will hide all functions.
        functions:
            enabled: true
            attribute: false
            user_editable: false

    # This basically says itself - Maybe false should be default, but at least
    # it'll show that registration is possible.
    # But if you want to turn this on you must also comment out the
    # registration routes in routing_custom.yml
    allow_registration: true

    # This also basically says itself, not really working well.
    enable_personal_messaging: false

    # The crew manager tab in the user frontend.
    enable_crew_manager: true

    # The role that will be applied.
    crew_manager_role: 'Crew Manager'

    # What constitutes a crew manager?
    crew_manager_functions:
        - 'Crew Manager'

    # For calculating days/times worked. Default 9 hours.
    full_day_minutes: 540

    # Job overlaps. A few options for it.
    
    # What is considered overlap? Only booked jobs if you ask me.
    job_overlap_booked_only: true

    # If any job the same day are to be considered overlap:
    job_overlap_same_day: true

    # Any job within less than these hours is considered an overlap
    # Set 0 if only pure overlap (Default)
    # job_overlap_hours: 4
    job_overlap_hours: 0

    bisonlab_reports.report_classes:
        - App\Lib\Reports\Reports
    # For generated reports, usuaslly uuseful to be able to grab from the web.
    bisonlab_reports.default_filestore: '%kernel.project_dir%/public/reports'

    crewcall.system_roles:
            ROLE_USER:
                label: 'Crewmember'
                description: 'User able to log into and use this application as crew member'
            ROLE_ADMIN:
                label: 'Admin'
                description: 'Admin User'
            ROLE_PERSON:
                label: 'Other'
                description: 'Person with other roles, like contact for an organization. Not able to log in.'

    # Stuff you can define in .env.local, if you want to.
    mailfrom: '%env(MAIL_FROM)%'
    mailname: '%env(MAIL_NAME)%'
