# This is made for your config stuff not common with CrewCall Base.
# parameters.yml is for the instance-specific config (DB username and password
# better not be common between dev and prod for example) , this is for the
# application specific.

parameters:
    # You may want to change these.
    # Languange - No translations yet, so this is mere sugar.
    locale: en_GB

    # Javascripts Intl uses two-letter locale. And it should be decided by the
    # browser/client. Somehow that is broken.
    javascript_locale: en

    # Fullcalendar also use locale, but it may not have what you set above.
    # Check https://github.com/fullcalendar/fullcalendar/tree/master/locales
    # Use the filename without .js
    # If you set "all" it will load the all.js file instead. It's close to 200K
    # where the separate files are 3K.
    fullcalendar_locale: en-gb

    # New users has to be connected to something by default. If it's a crew
    # member you want to connect it to your organization with a default role.
    # (This is a hen and egg situation since you haven't created your
    # organization when you set up this application. But there is a solutaion
    # to that. The name and role you put here will be created by the
    # once:create-base-data command.
    #
    # This is also what defines a crew member.
    internal_organization:
        name: "Internal"
        default_role: "Crewmember"
        # If you set this to false the organization and role above will be
        # added to all new crew members and no option to set others will be
        # shown. I'd guess this will not be used much.
        allow_external_crew: false

    # This is for setting up the address fields. Different countries has
    # different needs, so we need somewhere for defining those needs.
    # Fields you can use is in Entity/EmbeddableAddress in the CrewCallBundle
    # code.
    # Country differs that it will not be showwn if it is the default country.
    # The values here is the ones shown in the input and edit forms.
    addressing:
        # Mostly, postal address as an extra address is not used. If you want
        # it, set it to true.
        use_postal_address: false
        default_country_code: NO
        default_country_name: Norway
        format:
            - ['addressLine1']
            - ['addressLine2']
            - ['postalCode', 'postalName']
            - ['country']

    # This basically says itself - Maybe false should be default, but at least
    # it'll show that registration is possible.
    # But if you want to turn this on you must also comment out the
    # registration routes in routing_custom.yml
    allow_registration: true
    # This also basically says itself, not really working well.
    enable_personal_messaging: false

    bisonlab_reports.report_classes:
        - App\Lib\Reports\Reports
        # - CustomBundle\Lib\Reports\Reports
    # For generated reports, usuaslly uuseful to be able to grab from the web.
    bisonlab_reports.default_filestore: '%kernel.project_dir%/public/reports'

    crewcall.system_roles:
            ROLE_USER:
                label: 'Crewmember'
                description: 'User able to log into and use this application as crew member'
            ROLE_ADMIN:
                label: 'Admin'
                description: 'Admin User'
            ROLE_PERSON:
                label: 'Other'
                description: 'Person with other roles, like contact for an organization. Not able to log in.'

    # Stuff you can define in .env.local, if you want to.
    mailfrom: '%env(MAIL_FROM)%'
    mailname: '%env(MAIL_NAME)%'
