parameters:
    sakonnin.user:
        class: App:Person
        entity: \App\Entity\Person

    sakonnin.function_factories:
        - BisonLab\SakonninBundle\Lib\Sakonnin\SakonninFunctions
        - App\Lib\Sakonnin\SakonninFunctions
    # For the up/download of files attached to objects. This should not be
    # available from the web.
    sakonnin.file_storage: '%kernel.project_dir%/var/files'
    # When a message has "expires at" and reaches the expire date, do:
    sakonnin.expire_method: "Archive"
    # And when the message type expunge hits:
    sakonnin.expunge_method: "Delete"
    
    # Gotta be overridden in your custombundle sakonnin.yaml
    # (But better put password in .env.local :=)
    sakonnin.sms:
        sender: '%env(SMS_SENDER)%'
        receiver: '%env(SMS_RECEIVER)%'
        username: '%env(SMS_USERNAME)%'
        password: '%env(SMS_PASSWORD)%'
        sms_server_host: '%env(SMS_SERVER_HOST)%'
        sms_server_port: '%env(SMS_SERVER_PORT)%'
        smsfrom: '%env(SMS_FROM)%'
        smscode: '%env(SMS_CODE)%'
        mailfrom: '%env(SMS_MAIL_FROM)%'
        mailto: '%env(SMS_MAIL_TO)%'
        national_number_lenght: '%env(SMS_NATIONAL_NUMBER_LENGTH)%'
        default_country_prefix: '%env(SMS_DEFAULT_COUNTRY_PREFIX)%'


    # The simplest file types. Need to set it here to override the ones in the
    # Sakonnin Bundle.
    sakonnin.file_types:
        ProfilePicture:
            chooseable: true
            thumbnailable: true
        CV:
            chooseable: true
            thumbnailable: false
        Map:
            chooseable: true
            thumbnailable: false
        DOCUMENT:
            chooseable: true
            thumbnailable: false
        AUTO:
            chooseable: true
            thumbnailable: false
        IMAGE:
            chooseable: true
            thumbnailable: true
        TEXT:
            chooseable: true
            thumbnailable: false
        UNKNOWN:
            chooseable: true
            thumbnailable: false

services:
    sakonnin.sms_handler:
        public: true
        class: BisonLab\SakonninBundle\Service\SmsHandler
        arguments: ['@service_container', '%sakonnin.sms%']
