vich_uploader:
    db_driver: orm

    mappings:
        sakonnin_file:
            upload_destination: '%sakonnin.file_storage%'
            namer:
                service: vich_uploader.namer_property
                options: { property: 'fileId'}
