bison_lab_sakonnin:
    resource: "@BisonLabSakonninBundle/src/Controller/"
    type:     attribute
    prefix:   /

bisonlab_reports:
    resource: "@BisonLabReportsBundle/Controller/"
    type:     attribute
    prefix:   /

BisonLabCommonBundle:
    resource: "@BisonLabCommonBundle/Controller/"
    type:     attribute
    prefix:   /
