imports:
    - { resource: parameters.yml }
    - { resource: states.yml }
    - { resource: types.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@BisonLabCommonBundle/Resources/config/services.yml" }
    - { resource: "@CrewCallBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi:             ~
    translator:      { fallbacks: [en] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
    #serializer:      { enable_annotations: true }
    default_locale:  "%locale%"
    trusted_hosts:   ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        sakonnin_messages: "@sakonnin.messages"
        sakonnin_files:    "@sakonnin.files"
        cc_jobs:           "@crewcall.jobs"
        cc_formcreator:    "@crewcall.formcreator"
        states:            "%app.states%"
        types:             "%app.types%"

# Doctrine Configuration
doctrine:
    dbal:
        default_connection: crewcall
        connections:
            crewcall:
                driver:   pdo_pgsql
                host:     "%database_host%"
                port:     "%database_port%"
                dbname:   "%database_name%"
                user:     "%database_user%"
                password: "%database_password%"
                charset:  UTF8

    orm:
        default_entity_manager: crewcall
        auto_generate_proxy_classes: "%kernel.debug%"
        entity_managers:
            crewcall:
                # To have or not to have?
                # naming_strategy: doctrine.orm.naming_strategy.underscore
                connection: crewcall
                # auto_mapping: true
                mappings:
                    CustomBundle: ~
                    CrewCallBundle: ~
                    # No need for this one here, will use the Person entity.
                    # BisonLabCommonBundle: ~
                    FOSUserBundle: ~
                    gedmo_loggable:
                        type: annotation
                        prefix: Gedmo\Loggable\Entity
                        dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Loggable/Entity"
                        alias: GedmoLoggable
                        is_bundle: false
            sakonnin:
                # To have or not to have?
                # naming_strategy: doctrine.orm.naming_strategy.underscore
                connection: crewcall
                # auto_mapping: true
                mappings:
                    BisonLabSakonninBundle: ~

fos_user:
    db_driver: orm
    model_manager_name: crewcall
    firewall_name: main
    user_class: CrewCallBundle\Entity\Person
    change_password: true
    from_email:
        address:        erik@zelow.no
        sender_name:    CrewCall
    registration:
        form:
            type: CrewCallBundle\Form\RegistrationType
        confirmation:
            enabled:    true # change to true for required email confirmation
            template:   '@FOSUser/Registration/email.txt.twig'

stof_doctrine_extensions:
    default_locale: nb_NO
    orm:
        crewcall:
            loggable: true
            timestampable: true
            blameable: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

services:
    fos_user.doctrine_registry:
        alias: doctrine

assetic:
    debug:          '%kernel.debug%'
    use_controller: '%kernel.debug%'
    filters:
        less:
            node: /usr/bin/nodejs
            node_paths: ["/usr/local/lib/node_modules"]
            apply_to: '\.less$'
        cssrewrite: ~

jms_serializer:
    handlers:
        datetime:
            default_format: "c"
            default_timezone: "UTC" # defaults to whatever timezone set in php.ini or via date_default_timezone_set

    property_naming:
        separator:  _
        lower_case: true

    metadata:
        cache: file
        debug: "%kernel.debug%"
        file_cache:
            dir: "%kernel.cache_dir%/serializer"

        # Using auto-detection, the mapping files for each bundle will be
        # expected in the Resources/config/serializer directory.
        #
        # Example:
        # class: My\FooBundle\Entity\User
        # expected path: @MyFooBundle/Resources/config/serializer/Entity.User.(yml|xml|php)
        auto_detection: true

braincrafted_bootstrap:
    css_preprocessor: less
    jquery_path: '%kernel.root_dir%/../web/public/jquery/jquery.min.js'
    assets_dir: '%kernel.root_dir%/../vendor/twbs/bootstrap'
    fonts_dir: '%kernel.root_dir%/../web/public/fonts'
    output_dir: 'public'
    auto_configure:
        assetic: true
        twig: true
        knp_menu: true
        knp_paginator: true
    customize:
        variables_file: ~
        bootstrap_output: "%kernel.root_dir%/Resources/less/bootstrap.less"
        bootstrap_template: BraincraftedBootstrapBundle:Bootstrap:bootstrap.less.twig

vich_uploader:
    db_driver: orm
    mappings:
        sakonnin_file:
            upload_destination: '%sakonnin.file_storage%'
            namer:
                service: vich_uploader.namer_property
                options: { property: 'fileId'}
