# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: CustomBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    sakonnin.sms_handler:
        class: BisonLab\SakonninBundle\Service\SmsHandler
        arguments: 
            container: '@service_container'
            options: '%sakonnin.sms%'

